### ISSUE TITLE
virus, checked your commits for builder.py

### ISSUE THREAD

**Issue by hozzywozzy** [Yuvi5001/moon-grabber#10]
this "was" a virus you changed it to be random chinese jargon. You're a retard.

**Comment by fanta323** [comment]
kys

**Comment by fanta323** [comment]
if it even was a virus it would have already been deleted by github

**Comment by hozzywozzy** [comment]
Not true, I’ve reported another token logger and only just got a reply from github about them checking it out.

**Comment by fanta323** [comment]
wheres the virus located in then?

**Comment by fanta323** [comment]
If you could locate the virus, i could remove it since i know the owner, i can get him banned from my server.

**Comment by hozzywozzy** [comment]
> If you could locate the virus, i could remove it since i know the owner, i can get him banned from my server.

That's probably a good idea. If you just read through the commits on his github project you can see where he tried hiding and removing the token loggers from his files, Thats a good thing about github. I would report him/his project for malware.

**Comment by fanta323** [comment]
Thanks, i will delete that file ASAP! If you find any others i will be happy to delete it.

**Comment by hozzywozzy** [comment]
YUP! NP.

**Comment by fanta323** [comment]
do you know how to deobfuscate? i can't find a way to

**Comment by juan0077** [comment]
> this "was" a virus you changed it to be random chinese jargon. You're a retard.

Kiddo anime pfp detected, your opinion is rejected. Yuvi hasn’t made a virus dickhead

**Comment by hozzywozzy** [comment]
> > this "was" a virus you changed it to be random chinese jargon. You're a retard.
> 
> 
> 
> Kiddo anime pfp detected, your opinion is rejected. Yuvi hasn’t made a virus dickhead

LOL

**Comment by hozzywozzy** [comment]
> > this "was" a virus you changed it to be random chinese jargon. You're a retard.
> 
> Kiddo anime pfp detected, your opinion is rejected. Yuvi hasn’t made a virus dickhead

LOLOLOLOLOLOLOL ALT ACCOUNT LMAOOOOOOOOOOOOOOOOOOooo

![image](https://user-images.githubusercontent.com/87353619/219441125-6e950819-9994-41e6-abc8-1e87400d5979.png)
 THAT IS SOOOOOOOOOOOOOOOOOOO SAD

**Comment by Yuvi5001** [comment]
@hozzywozzy deleted

**Comment by Yuvi5001** [comment]
virus removed (CHANGE UR PASSWORD TO EVERYONE WHO RAN IT AND RUN A SCAN)

one of our teammates added a batware.

**Comment by hozzywozzy** [comment]
> virus removed (CHANGE UR PASSWORD TO EVERYONE WHO RAN IT AND RUN A SCAN)
> 
> one of our teammates added a batware.

Liar. Its sad that you're trying to playing that BS, just SAD.
