### ISSUE TITLE
skid

### ISSUE THREAD

**Issue by hozzywozzy** [Yuvi5001/moon-grabber#9]
write your own code

**Comment by fanta323** [comment]
no shit sherlock

**Comment by fanta323** [comment]
better than wasp

**Comment by juan0077** [comment]
> write your own code

Shut up little bitch you literally made a repo and wrote “I haven’t made this, using it for my own utility” dumb little fucking bitch commenting behind his little asus laptop

**Comment by hozzywozzy** [comment]
no just commenting on my phone, somebody’s maddddddd it’s not that deep you whining cunt  😂😂😂

**Comment by hozzywozzy** [comment]
> > write your own code
> 
> Shut up little bitch you literally made a repo and wrote “I haven’t made this, using it for my own utility” dumb little fucking bitch commenting behind his little asus laptop

like i didnt even need to credit the author cause it was already credited, + what does a roblox script frontend have to do with this at all like wtf. you're reallllllllllllllllll mad for no reason at all LMAO.

**Comment by Yuvi5001** [comment]
its alr
